import { t } from './time';
import {
  ProducerData,
  ProductionData,
} from './types';

const ALL_PRODUCERES: ProducerData[] = [
  { name: 'Factory', slots: 5 },
  { name: 'Building Supplies Store', slots: 11, sequential: true },
  { name: 'Hardware Store', slots: 11, sequential: true },
  { name: "Farmer's Market", slots: 11, sequential: true },
  { name: 'Furniture Store', slots: 10, sequential: true },
  { name: 'Gardening Supplies', slots: 10, sequential: true },
  { name: 'Donut Shop', slots: 7, sequential: true },
  { name: 'Fashion Store', slots: 11, sequential: true },
  { name: 'Fast Food Restaurant', slots: 9, sequential: true },
  { name: 'Home Appliances', slots: 11, sequential: true },
];

const ALL_PRODUCTIONS: ProductionData[] = [
  // Factory
  {
    name: 'Metal',
    time: t('1m'),
    price: 10,
    producer: 'Factory',
  },
  {
    name: 'Wood',
    time: t('3m'),
    price: 20,
    producer: 'Factory',
  },
  {
    name: 'Plastic',
    time: t('9m'),
    price: 25,
    producer: 'Factory',
  },
  {
    name: 'Seeds',
    time: t('20m'),
    price: 30,
    producer: 'Factory',
  },
  {
    name: 'Minerals',
    time: t('30m'),
    price: 40,
    producer: 'Factory',
  },
  {
    name: 'Chemicals',
    time: t('2h'),
    price: 60,
    producer: 'Factory',
  },
  {
    name: 'Textiles',
    time: t('3h'),
    price: 90,
    producer: 'Factory',
  },
  {
    name: 'Sugar and Spices',
    time: t('4h'),
    price: 110,
    producer: 'Factory',
  },
  {
    name: 'Glass',
    time: t('5h'),
    price: 120,
    producer: 'Factory',
  },
  {
    name: 'Animal Feed',
    time: t('6h'),
    price: 140,
    producer: 'Factory',
  },
  {
    name: 'Electrical Components',
    time: t('7h'),
    price: 160,
    producer: 'Factory',
  },
  // Building Supplies Store
  {
    name: 'Nails',
    time: t('4m'),
    price: 80,
    producer: 'Building Supplies Store',
    requirements: ['Metal', 'Metal'],
  },
  {
    name: 'Planks',
    time: t('24m'),
    price: 120,
    producer: 'Building Supplies Store',
    requirements: ['Wood', 'Wood'],
  },
  {
    name: 'Bricks',
    time: t('16m'),
    price: 190,
    producer: 'Building Supplies Store',
    requirements: ['Minerals', 'Minerals'],
  },
  {
    name: 'Cement',
    time: t('40m'),
    price: 440,
    producer: 'Building Supplies Store',
    requirements: ['Minerals', 'Minerals', 'Chemicals'],
  },
  {
    name: 'Glue',
    time: t('48m'),
    price: 440,
    producer: 'Building Supplies Store',
    requirements: ['Plastic', 'Chemicals', 'Chemicals'],
  },
  {
    name: 'Paint',
    time: t('48m'),
    price: 320,
    producer: 'Building Supplies Store',
    requirements: ['Metal', 'Minerals', 'Chemicals', 'Chemicals'],
  },
  // Hardware Store
  {
    name: 'Hammer',
    time: t('11m12s'),
    price: 90,
    producer: 'Hardware Store',
    requirements: ['Metal', 'Wood'],
  },
  {
    name: 'Measuring Tape',
    time: t('16m'),
    price: 110,
    producer: 'Hardware Store',
    requirements: ['Metal', 'Plastic'],
  },
  {
    name: 'Shovel',
    time: t('24m'),
    price: 150,
    producer: 'Hardware Store',
    requirements: ['Metal', 'Plastic', 'Wood'],
  },
  {
    name: 'Cooking Utensils',
    time: t('36m'),
    price: 250,
    producer: 'Hardware Store',
    requirements: ['Metal', 'Plastic', 'Wood', 'Metal', 'Plastic', 'Wood'],
  },
  {
    name: 'Ladder',
    time: t('48m'),
    price: 420,
    producer: 'Hardware Store',
    requirements: ['Metal', 'Planks', 'Metal', 'Planks'],
  },
  {
    name: 'Drill',
    time: t('1h36m'),
    price: 590,
    producer: 'Hardware Store',
    requirements: ['Metal', 'Metal', 'Plastic', 'Plastic', 'Electrical Components'],
  },
  // Farmer's Market
  {
    name: 'Vegetables',
    time: t('16m'),
    price: 160,
    producer: "Farmer's Market",
    requirements: ['Seeds', 'Seeds'],
  },
  {
    name: 'Flour Bag',
    time: t('24m'),
    price: 570,
    producer: "Farmer's Market",
    requirements: ['Seeds', 'Seeds', 'Textiles', 'Textiles'],
  },
  {
    name: 'Fruit and Berries',
    time: t('1h12m'),
    price: 730,
    producer: "Farmer's Market",
    requirements: ['Seeds', 'Seeds', 'Tree Sapling'],
  },
  {
    name: 'Cream',
    time: t('1h'),
    price: 440,
    producer: "Farmer's Market",
    requirements: ['Animal Feed'],
  },
  {
    name: 'Corn',
    time: t('48m'),
    price: 280,
    producer: "Farmer's Market",
    requirements: ['Minerals', 'Seeds', 'Seeds', 'Seeds', 'Seeds'],
  },
  {
    name: 'Cheese',
    time: t('1h24m'),
    price: 660,
    producer: "Farmer's Market",
    requirements: ['Animal Feed', 'Animal Feed'],
  },
  {
    name: 'Beef',
    time: t('2h'),
    price: 860,
    producer: "Farmer's Market",
    requirements: ['Animal Feed', 'Animal Feed', 'Animal Feed'],
  },
  // Furniture Store
  {
    name: 'Chair',
    time: t('16m'),
    price: 300,
    producer: 'Furniture Store',
    requirements: ['Wood', 'Wood', 'Hammer', 'Nails'],
  },
  {
    name: 'Table',
    time: t('24m'),
    price: 500,
    producer: 'Furniture Store',
    requirements: ['Nails', 'Nails', 'Planks', 'Hammer'],
  },
  {
    name: 'Home Textile',
    time: t('1h'),
    price: 610,
    producer: 'Furniture Store',
    requirements: ['Textiles', 'Textiles', 'Measuring Tape'],
  },
  {
    name: 'Cupboard',
    time: t('36m'),
    price: 900,
    producer: 'Furniture Store',
    requirements: ['Glass', 'Glass', 'Planks', 'Planks', 'Paint'],
  },
  {
    name: 'Couch',
    time: t('2h'),
    price: 1810,
    producer: 'Furniture Store',
    requirements: ['Textiles', 'Textiles', 'Textiles', 'Glue', 'Drill'],
  },
  // Gardening Supplies
  {
    name: 'Grass',
    time: t('24m'),
    price: 310,
    producer: 'Gardening Supplies',
    requirements: ['Shovel', 'Seeds'],
  },
  {
    name: 'Tree Sapling',
    time: t('1h12m'),
    price: 420,
    producer: 'Gardening Supplies',
    requirements: ['Shovel', 'Seeds', 'Seeds'],
  },
  {
    name: 'Garden Furniture',
    time: t('1h48m'),
    price: 820,
    producer: 'Gardening Supplies',
    requirements: ['Plastic', 'Plastic', 'Textiles', 'Textiles', 'Planks', 'Planks'],
  },
  {
    name: 'Lawn Mower',
    time: t('1h36m'),
    price: 840,
    producer: 'Gardening Supplies',
    requirements: ['Metal', 'Metal', 'Metal', 'Electrical Components', 'Paint'],
  },
  {
    name: 'Fire Pit',
    time: t('3h12m'),
    price: 1740,
    producer: 'Gardening Supplies',
    requirements: ['Bricks', 'Bricks', 'Cement', 'Cement', 'Shovel'],
  },
  {
    name: 'Garden Gnome',
    time: t('1h12m'),
    price: 1600,
    producer: 'Gardening Supplies',
    requirements: ['Cement', 'Cement', 'Glue'],
  },
  // Donut Shop
  {
    name: 'Donuts',
    time: t('36m'),
    price: 950,
    producer: 'Donut Shop',
    requirements: ['Flour Bag', 'Sugar and Spices'],
  },
  {
    name: 'Green Smoothie',
    time: t('24m'),
    price: 1150,
    producer: 'Donut Shop',
    requirements: ['Fruit and Berries', 'Vegetables'],
  },
  {
    name: 'Bread Roll',
    time: t('48m'),
    price: 1840,
    producer: 'Donut Shop',
    requirements: ['Flour Bag', 'Flour Bag', 'Cream'],
  },
  {
    name: 'Cherry Cheesecake',
    time: t('1h12m'),
    price: 2240,
    producer: 'Donut Shop',
    requirements: ['Flour Bag', 'Fruit and Berries', 'Cheese'],
  },
  {
    name: 'Frozen Yogurt',
    time: t('3h12m'),
    price: 1750,
    producer: 'Donut Shop',
    requirements: ['Fruit and Berries', 'Sugar and Spices', 'Cream'],
  },
  {
    name: 'Coffee',
    time: t('48m'),
    price: 750,
    producer: 'Donut Shop',
    requirements: ['Sugar and Spices', 'Cream', 'Seeds', 'Seeds'],
  },
  // Fashion Store
  {
    name: 'Cap',
    time: t('48m'),
    price: 600,
    producer: 'Fashion Store',
    requirements: ['Textiles', 'Textiles', 'Measuring Tape'],
  },
  {
    name: 'Shoes',
    time: t('1h'),
    price: 980,
    producer: 'Fashion Store',
    requirements: ['Plastic', 'Textiles', 'Textiles', 'Glue'],
  },
  {
    name: 'Watch',
    time: t('1h12m'),
    price: 580,
    producer: 'Fashion Store',
    requirements: ['Plastic', 'Plastic', 'Chemicals', 'Glass'],
  },
  {
    name: 'Business Suit',
    time: t('2h48m'),
    price: 1170,
    producer: 'Fashion Store',
    requirements: ['Textiles', 'Textiles', 'Textiles', 'Glue', 'Measuring Tape'],
  },
  {
    name: 'Backpack',
    time: t('2h'),
    price: 430,
    producer: 'Fashion Store',
    requirements: ['Plastic', 'Plastic', 'Textiles', 'Textiles', 'Measuring Tape'],
  },
  // Fast Food Restaurant
  {
    name: 'Ice Cream Sandwich',
    time: t('11m54s'),
    price: 2256,
    producer: 'Fast Food Restaurant',
    requirements: ['Cream', 'Bread Roll'],
  },
  {
    name: 'Pizza',
    time: t('20m24s'),
    price: 2560,
    producer: 'Fast Food Restaurant',
    requirements: ['Flour Bag', 'Cheese', 'Beef'],
  },
  {
    name: 'Burger',
    time: t('29m45s'),
    price: 3620,
    producer: 'Fast Food Restaurant',
    requirements: ['Beef', 'Bread Roll', 'BBQ Grill'],
  },
  {
    name: 'Cheese Fries',
    time: t('17m'),
    price: 1050,
    producer: 'Fast Food Restaurant',
    requirements: ['Cheese', 'Vegetables'],
  },
  {
    name: 'Lemonade Bottle',
    time: t('51m'),
    price: 1690,
    producer: 'Fast Food Restaurant',
    requirements: ['Glass', 'Glass', 'Sugar and Spices', 'Sugar and Spices', 'Fruit and Berries'],
  },
  {
    name: 'Popcorn',
    time: t('25m30s'),
    price: 1250,
    producer: 'Fast Food Restaurant',
    requirements: ['Microwave Oven', 'Corn', 'Corn'],
  },
  // Home Appliances
  {
    name: 'BBQ Grill',
    time: t('2h28m'),
    price: 530,
    producer: 'Home Appliances',
    requirements: ['Metal', 'Metal', 'Metal', 'Cooking Utensils'],
  },
  {
    name: 'Refrigerator',
    time: t('3h9m'),
    price: 1060,
    producer: 'Home Appliances',
    requirements: [
      'Plastic',
      'Plastic',
      'Chemicals',
      'Chemicals',
      'Electrical Components',
      'Electrical Components',
    ],
  },
  {
    name: 'Lighting System',
    time: t('1h34m'),
    price: 890,
    producer: 'Home Appliances',
    requirements: ['Chemicals', 'Glass', 'Electrical Components'],
  },
  {
    name: 'TV',
    time: t('2h15m'),
    price: 1280,
    producer: 'Home Appliances',
    requirements: [
      'Plastic',
      'Plastic',
      'Glass',
      'Glass',
      'Electrical Components',
      'Electrical Components',
    ],
  },
  {
    name: 'Microwave Oven',
    time: t('1h48m'),
    price: 480,
    producer: 'Home Appliances',
    requirements: ['Metal', 'Metal', 'Metal', 'Metal', 'Glass', 'Electrical Components'],
  },
];

export { ALL_PRODUCERES, ALL_PRODUCTIONS };
